version: 0.0.1.{build}

image: Visual Studio 2017

shallow_clone: true

cache:
  - "%LOCALAPPDATA%\\Programs\\stack"
  - "%APPDATA%\\stack"
  - .stack-work

build_script:
  - choco install haskell-stack
  - stack --no-terminal setup > NUL
  - stack --no-terminal exec pacman -- -Syu --noconfirm
  - stack --no-terminal exec pacman -- -Syu --noconfirm
  - stack --no-terminal build --haddock --haddock-deps --test --no-run-tests

test_script:
  - stack --no-terminal test
