name: msbuild
version: 0.0.1
category: Compiler
synopsis: Utilities for working with MSBuild in Haskell.
maintainer: Shao Cheng <astrohavoc@gmail.com>
copyright: (c) 2017 Shao Cheng
license: BSD3
github: TerrorJack/msbuild

extra-source-files:
  - LICENSE
  - README.md

data-files:
  - utils/vswhere.exe

ghc-options: -Wall

dependencies:
  - aeson
  - base
  - bytestring
  - directory
  - filepath
  - process
  - process-extras
  - text
  - time

library:
  source-dirs: src
  other-modules:
    - Paths_msbuild
  other-extensions:
    - TemplateHaskell

tests:
  msbuild-test:
    source-dirs: test
    main: msbuild-test.hs
    dependencies:
      - msbuild
